# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: ./run configure

    - name: Build
      run: ./run build

  format:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: ./run configure

    - name: Check formatting
      run: ./run format-check-ci

  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Configure
      run: ./run configure --no-ui-tools

    - name: Test
      run: ./run test
